# Generated by Django 4.2 on 2023-05-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.OneToOneField(on_delete=models.SET('<deleted>'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('easy_count', models.IntegerField()),
                ('easy_answered', models.IntegerField()),
                ('medium_count', models.IntegerField()),
                ('medium_answered', models.IntegerField()),
                ('hard_count', models.IntegerField()),
                ('hard_answered', models.IntegerField()),
                ('easy_total_time', models.FloatField()),
                ('medium_total_time', models.FloatField()),
                ('hard_total_time', models.FloatField()),
                ('easy_total_time_answered', models.FloatField()),
                ('medium_total_time_answered', models.FloatField()),
                ('hard_total_time_answered', models.FloatField()),
                ('difficulty', models.ForeignKey(on_delete=models.SET('<deleted>'), to='quiz.difficulties')),
                ('format', models.ForeignKey(on_delete=models.SET('<deleted>'), to='quiz.formats')),
                ('least_answered_category', models.ForeignKey(on_delete=models.SET('<deleted>'), related_name='least_answered', to='quiz.categories')),
                ('most_answered_category', models.ForeignKey(on_delete=models.SET('<deleted>'), related_name='most_answered', to='quiz.categories')),
                ('session', models.ForeignKey(null=True, on_delete=models.SET('<deleted>'), to='quiz.sessions')),
                ('user', models.ForeignKey(on_delete=models.SET('<deleted>'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('priority', models.IntegerField(default=15)),
                ('asked', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.answers')),
                ('category', models.ForeignKey(on_delete=models.SET('<deleted>'), to='quiz.categories')),
                ('difficulty', models.ForeignKey(on_delete=models.SET('<deleted>'), to='quiz.difficulties')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.customtitles')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questions'),
        ),
        migrations.AddConstraint(
            model_name='tests',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unique_user_session_combination'),
        ),
        migrations.AddConstraint(
            model_name='customtitles',
            constraint=models.UniqueConstraint(fields=('title', 'host'), name='each_host_has_unique_title'),
        ),
    ]
